package internal

import (
	"errors"
	"fmt"
	"os"

	"github.com/spf13/pflag"
)

const (
	usage = `yasp - split and validate yaml document

  yasp [flags] COMMAND...

# Usage by Example

  yasp -i 'id' some_linter < some_manifest

Read yaml from stdin, split into documents, run some_linter for each document.
A document passed as a file, like some_linter DOCUMENT_FILE.
Display the result if some_linter failed as below:

--- DOCUMENT_ID some_linter
stdout and stderr of some_linter

DOCUMENT_ID is an id to identify the document, generated by 'id' applied to the document.

  yasp -i 'id' some_linter another_linter < some_manifest

Run some_linter and another_linter for each document.
A document fails if either of them failed.

  yasp -i 'id' -o verbose some_linter < some_manifest

Display the result even if some_linter succeeded.

  yasp -i 'id' -o yaml some_linter < some_manifest

Display the result as yaml:

- command: some_linter
  data: yaml document to be validated
  err: error message
  exitcode: exit code of some_linter
  id: document id
  stdout: stdout of some_linter
  stderr: stderr of some_linter

A summary will be displayed at the end:

Summary: x1 document, x2 invalid, x3 processed, x4 failed, x5 passed, x6 denied

means

- yasp read x1 documents
- but x2 documents are broken or no id
- x3 documents are checked
- but x4 documents cannot be checked
- x5 documents are green
- x6 documents are red

with -o verbose, like:

document.command.some_linter.count x1, document.command.some_linter.denined x2, document.command some_linter.passed x3, document.count x4, document.process.count x5, document.process.denined x6

with -o yaml, like:

- summary:
  - metric: document.command.some_linter.count
    value: x1
  - metric: document.command.some_linter.denied
    value: x2
  - metric: document.command.some_linter.passed
    value: x3
  - metric: document.count
    value: x4
  - metric: document.process.count
    value: x5
  - metric: document.process.denied
    value: x7

  yasp -k KUSTOMIZE_ROOT -b some_linter

Render kustomization and save it as a file, run some_linter to the file for each kustomization.yaml under KUSTOMIZE_ROOT.

# Exit status

0 if all documents are green.
Otherwise 1.
`
)

const k8sIDTemplate = `apiVersion + ">" + kind + ">" + (metadata.namespace ?? "") + ">" + metadata.name`

var (
	ErrHelp          = errors.New("Help")
	ErrInvalidConfig = errors.New("InvalidConfig")
)

func parseFlags(args ...string) (*Config, error) {
	fs := pflag.NewFlagSet("main", pflag.ContinueOnError)
	fs.Usage = func() {
		fmt.Print(usage)
		fs.PrintDefaults()
	}

	var c Config
	fs.BoolVar(&c.Debug, "debug", false, "enable debug log")
	fs.StringVarP(&c.WorkDir, "workDir", "w", "", "change the working directory and disable cleanup")
	fs.StringVarP(&c.IDTemplate, "id", "i", "", `expr-lang expression to generate id to identify a yaml document`)
	fs.BoolVar(&c.K8SIDTemplate, "k8s", false, "use k8s id template: "+k8sIDTemplate)
	fs.StringVar(&c.Shell, "shell", "bash", "shell to execute commands")
	fs.BoolVar(&c.FailFast, "failfast", false, "fail yasp if a yaml document failed")
	fs.BoolVar(&c.FailFastCmd, "failfastcmd", false, "fail a yaml document if a check of the document failed")
	fs.BoolVar(&c.Success, "success", false, "exit with 0 even if failed")
	fs.StringVar(&c.Kubectl, "kubectl", "kubectl", "kubectl command")
	fs.StringVar(&c.Helm, "helm", "helm", "helm command")
	fs.StringVarP(&c.KustomizeRoot, "kustomizeRoot", "k", "", "directory that contains kustomization.yaml")
	fs.StringVarP(&c.HelmRoot, "helmRoot", "r", "", "directory that contains Chart.yaml")
	fs.BoolVarP(&c.Bulk, "bulk", "b", false, "do not split yaml document")
	fs.FuncP("out", "o", "output mode: text, verbose, yaml, yml", func(s string) error {
		switch s {
		case "text", "":
			c.Output = OutputModeText
		case "verbose":
			c.Output = OutputModeVerbose
		case "yaml", "yml":
			c.Output = OutputModeYaml
		default:
			return fmt.Errorf("%w: Unknown out: %s", ErrInvalidConfig, s)
		}
		return nil
	})

	err := fs.Parse(args)
	if errors.Is(err, pflag.ErrHelp) {
		return nil, ErrHelp
	}
	if err != nil {
		return nil, err
	}

	setupLogger(os.Stderr, c.Debug)

	c.Cmds = fs.Args()
	if len(c.Cmds) == 0 {
		return nil, fmt.Errorf("%w: no commands", ErrInvalidConfig)
	}
	if c.K8SIDTemplate {
		c.IDTemplate = k8sIDTemplate
	}
	if !c.Bulk && c.IDTemplate == "" {
		return nil, fmt.Errorf("%w: no id template", ErrInvalidConfig)
	}

	return &c, nil
}
