package internal

import (
	"context"
	"encoding/json"
	"fmt"
	"io"

	"github.com/goccy/go-yaml"
)

const UnknownDocumentID = "__unknown_document_id__"

type Document struct {
	ID   string
	Data string
	Err  error
}

type DocumentList struct {
	Items []*Document
}

// Load yaml documents from r.
func Load(ctx context.Context, r io.Reader, idTmpl string) (*DocumentList, error) {
	idGenerator, err := NewIDGenerator(idTmpl)
	if err != nil {
		return nil, err
	}

	um := NewYamlUnmarshaler[map[string]any](r, true)
	xs, err := um.Unmarshal(ctx)
	if err != nil {
		return nil, err
	}

	m := NewYamlMarshaler(2, true)

	items := make([]*Document, len(xs))
	for i, x := range xs {
		d, err := m.Marshal(ctx, x)
		if err != nil {
			items[i] = &Document{
				ID:   UnknownDocumentID,
				Err:  fmt.Errorf("%w: failed to generate id, marshal to remarshal, index=%d", err, i),
				Data: string(d),
			}
			continue
		}

		// The object x contains yaml types because it was generated by yaml.Unmarshal
		// so remove them by remarshal via json.
		jb, err := yaml.YAMLToJSON(d)
		if err != nil {
			items[i] = &Document{
				ID:   UnknownDocumentID,
				Err:  fmt.Errorf("%w: failed to generate id, yaml to json, index=%d", err, i),
				Data: string(d),
			}
			continue
		}

		bm := map[string]any{}
		if err := json.Unmarshal(jb, &bm); err != nil {
			items[i] = &Document{
				ID:   UnknownDocumentID,
				Err:  fmt.Errorf("%w: failed to generate id, remarshal, index=%d", err, i),
				Data: string(d),
			}
			continue
		}

		id, err := idGenerator.GenerateID(bm)
		if err != nil {
			items[i] = &Document{
				ID:   UnknownDocumentID,
				Err:  fmt.Errorf("%w: failed to generate id, index=%d", err, i),
				Data: string(d),
			}
			continue
		}

		items[i] = &Document{
			ID:   id,
			Err:  err,
			Data: string(d),
		}
	}

	return &DocumentList{
		Items: items,
	}, nil
}
